services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    command: server /mnt/data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"

  jobmanager:
    build: .
    image: jobmanager
    container_name: jobmanager
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    ports:
      - "8081:8081"

  taskmanager:
    build: .
    image: taskmanager
    container_name: taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    depends_on:
      - jobmanager

  trino:
    image: trinodb/trino:latest
    container_name: trino
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge



