# docker network create bigdata
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    restart: always
    command: server /mnt/data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - bigdata

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    networks:
      - bigdata

  jobmanager:
    container_name: jobmanager
    image: jobmanager
    build: .
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    ports:
      - "8081:8081"
    networks:
      - bigdata

  taskmanager:
    container_name: taskmanager
    image: taskmanager
    build: .
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    depends_on:
      - jobmanager
    networks:
      - bigdata

  trino:
    container_name: trino
    image: trinodb/trino:latest
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    ports:
      - "8080:8080"
    networks:
      - bigdata

networks:
  bigdata:
    external: true


