coordinator=true
node-scheduler.include-coordinator=true
http-server.http.bind-address=0.0.0.0
http-server.http.port=8080

# 1. 开启账号密码认证
http-server.authentication.type=PASSWORD

# 2. 指定密码凭证校验器类型为文件 (PASSWORD_FILE)
authentication.password-file.auth-type=FILE
authentication.password-file.filename=/etc/trino/password.properties

